name: tfg-hiking-trails-app

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./../api-gateway
      dockerfile: HikingTrails.ApiGateway/Dockerfile
    restart: always
    env_file:
      - ./config/auth-service.env
    ports:
      - '5000:8080'
    depends_on:
      - auth-service

  auth-service:
    container_name: auth-service
    build:
      context: ./../auth-service
      dockerfile: AuthService.API/Dockerfile
    restart: always
    env_file:
      - ./config/auth-service.env
    expose:
      - '8080' # The microservice is no longer exposed externally so that it can only be accessed internally through my API Gateway.
    depends_on:
      - db-auth-service

  db-auth-service:
    container_name: db-auth-service
    image: mariadb:12.0.1-ubi9-rc
    restart: always
    env_file:
      - ./config/auth-service.env
    ports:
      - '3306:3306'
    volumes:
      # This volume is used to persist the database data
      - db-auth-service:/var/lib/mysql
      # Script to initialize the database
      - ./scripts/auth-service:/docker-entrypoint-initdb.d:ro

volumes:
  db-auth-service: