name: TFG-Hiking-Trails-App

services:
  auth-service:
    container_name: auth-service
    build:
      context: ./../auth-service
      dockerfile: AuthService/Dockerfile
    env_file:
      - ./config/auth-service.env
    ports:
      - "5000:8080"
    depends_on:
      - db-auth-service

  db-auth-service:
    container_name: db-auth-service
    image: mariadb:lts-noble
    env_file:
      - ./config/auth-service.env
    ports:
      - '3306:3306'
    volumes:
      # This volume is used to persist the database data
      - db-auth-service:/var/lib/mysql
      # Script to initialize the database
      - ./scripts/auth-service:/docker-entrypoint-initdb.d:ro

volumes:
  db-auth-service: